# Generated by Django 5.0.4 on 2024-12-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_content_description_content_album_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='ai_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
