# Generated by Django 5.0.4 on 2024-12-11 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_content_ai_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('spotify_url', models.URLField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='api.content')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
