# Generated by Django 5.0.4 on 2024-12-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contentsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
