# Generated by Django 5.0.4 on 2024-12-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_spotifytoken_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsuggestion',
            name='type',
            field=models.CharField(choices=[('track', 'Track'), ('artist', 'Artist'), ('album', 'Album')], default='track', max_length=10),
        ),
    ]
