# Generated by Django 5.0.4 on 2024-12-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_contentsuggestion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default='', help_text='A brief description about the user or their profile.', max_length=500),
        ),
    ]
