# Generated by Django 5.0.4 on 2024-12-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="User's date of birth (used to calculate age).", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture.', null=True, upload_to='profile_pictures/'),
        ),
    ]
