export type PostDetails = {
  id: number;
  imageUrl: string | null;
  title: string | undefined;
  content: string;
  username: string;
  likes: number;
  dislikes: number;
  created_at: Date;
  type: string;
  spotifyId: string;
  userAction: string | null;
};

export let mockPosts: PostDetails[] = [
  {
    id: 11,
    imageUrl: null,
    title: undefined,
    content:
      "Selamlarr, şöyle bir playlist hazırladım. Ortamlarda çalarsınız :)",
    username: "ekrembal",
    likes: 10,
    dislikes: 5,
    created_at: new Date(),
    type: "playlist",
    spotifyId: "3oAH9FsuQGzqP5hAHiEcFD",
    userAction: "like",
  },
  {
    id: 12,
    imageUrl: null,
    title: undefined,
    content: "I really like this song",
    username: "trella",
    likes: 10,
    dislikes: 5,
    created_at: new Date(),
    type: "track",
    spotifyId: "7x76RN4ZCsw5DxT8LOmexq",
    userAction: null,
  },
  {
    id: 13,
    imageUrl: null,
    title: undefined,
    content: "Мне очень нравится этот альбом",
    username: "нравьбом",
    likes: 1,
    dislikes: 2,
    created_at: new Date(),
    type: "album",
    spotifyId: "6RFizmJ3VitZBr8kwo62Kq",
    userAction: "dislike",
  },
  {
    id: 1,
    imageUrl: null,
    title: undefined,
    content:
      "Check out this track: 'New Person, Same Old Mistakes' by Tame Impala. It's amazing!",
    username: "ekrembal",
    likes: 15,
    dislikes: 3,
    created_at: new Date(),
    type: "track",
    spotifyId: "52ojopYMUzeNcudsoz7O9D",
    userAction: "like",
  },
  {
    id: 2,
    imageUrl: null,
    title: undefined,
    content: "I'm vibing with 'The Finishing'. Give it a listen!",
    username: "trella",
    likes: 20,
    dislikes: 1,
    created_at: new Date(),
    type: "track",
    spotifyId: "2SCLswvRP8hAYdIKsrLV6h",
    userAction: null,
  },
  {
    id: 3,
    imageUrl: null,
    title: undefined,
    content: "Burning Hour is on repeat for me today. Great track!",
    username: "nate",
    likes: 12,
    dislikes: 2,
    created_at: new Date(),
    type: "track",
    spotifyId: "2dje3ZBu1j1r0QfR7mtS0l",
    userAction: "like",
  },
  {
    id: 4,
    imageUrl: null,
    title: undefined,
    content: "Are You There is perfect for a chill evening.",
    username: "musiclover",
    likes: 18,
    dislikes: 0,
    created_at: new Date(),
    type: "track",
    spotifyId: "1LuK2NE1dkha6A4Cey3tsA",
    userAction: null,
  },
  {
    id: 5,
    imageUrl: null,
    title: undefined,
    content: "I'm really into '24/7'. Listen to it if you haven't yet!",
    username: "ekrembal",
    likes: 25,
    dislikes: 4,
    created_at: new Date(),
    type: "track",
    spotifyId: "4UySkSnMBKf1PS32agnwxp",
    userAction: "like",
  },
  {
    id: 6,
    imageUrl: null,
    title: undefined,
    content: "Vanity Corner is such a unique track. What do you think?",
    username: "nate",
    likes: 8,
    dislikes: 1,
    created_at: new Date(),
    type: "track",
    spotifyId: "2e7CRfHmTnrT5SxfXbQ0lF",
    userAction: null,
  },
  {
    id: 7,
    imageUrl: null,
    title: undefined,
    content: "I made this playlist 'nE'. Let me know your thoughts!",
    username: "ekrembal",
    likes: 30,
    dislikes: 5,
    created_at: new Date(),
    type: "playlist",
    spotifyId: "0Ljm42Eo0Ia1bDuw6sGvVI",
    userAction: "like",
  },
  {
    id: 8,
    imageUrl: null,
    title: undefined,
    content: "The 'zıbar' playlist is perfect for chilling. Check it out!",
    username: "trella",
    likes: 22,
    dislikes: 3,
    created_at: new Date(),
    type: "playlist",
    spotifyId: "7kbGTNApfe03SjBDIFrQ3B",
    userAction: null,
  },
  {
    id: 9,
    imageUrl: null,
    title: undefined,
    content: "Dive deep into my 'POSEIDON' playlist! Hope you enjoy.",
    username: "нравьбом",
    likes: 16,
    dislikes: 2,
    created_at: new Date(),
    type: "playlist",
    spotifyId: "6fMfMHqUS72fM3YS8MDKtr",
    userAction: "dislike",
  },
  {
    id: 10,
    imageUrl: null,
    title: undefined,
    content: "Here's a great Techno playlist I've been enjoying lately!",
    username: "musiclover",
    likes: 28,
    dislikes: 1,
    created_at: new Date(),
    type: "playlist",
    spotifyId: "24ztzWYSKzrV8G5OiMw8yS",
    userAction: null,
  },
];
