name: Generate an Issue
description: Report a bug, request a feature, ask a question related to the course or open an issue for deliverables.
title: "[Type]: Brief Description"
labels: ["pending triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for taking the time to file an issue!
        Please fill out this template with all the relevant information so we can understand what's going on and address the issue.

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of issue are you creating?
      options:
        - Bug Report
        - Feature Request
        - Deliverable
        - General Question
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Please provide a detailed description of the issue.
      placeholder: Describe the issue or your question in as much detail as possible.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: If reporting a bug, provide steps to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false

  - type: input
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: If reporting a bug, describe what you expected to happen.
      placeholder: e.g., The page should load without errors.
    validations:
      required: false

  - type: input
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: If reporting a bug, describe what actually happened.
      placeholder: e.g., The page crashes and shows an error message.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the issue here.
      placeholder: You can also attach links to documents or images here.
    validations:
      required: false

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: Please ensure you have read and agree to our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
