name: Generate an Issue
description: Report a bug or open an issue for deliverables. Please do not forget to specify Project, Milestone, Priority, Size, Start and End date fields.
title: "[Type]: Brief Description"
labels: ["pending triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for taking the time to file an issue!
        Please fill out this template with all the relevant information so we can understand what's going on and address the issue.

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of issue are you creating?
      options:
        - Bug Report
        - Feature Request
        - Deliverable
        - General Question
        - Wiki
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Please provide a detailed description of the issue.
      placeholder: Describe the issue or your question in as much detail as possible.
    validations:
      required: true


  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the issue here.
      placeholder: You can also attach links to documents or images here.
    validations:
      required: false
