version: '3.9'

services:

  # Database service
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  # Adminer for database management
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # Backend service
  backend:
    build: ../backend
    container_name: backend
    command: bash -c "sleep 3 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../backend:/backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SPOTIFY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI} 
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DEBUG: ${DJANGO_DEBUG}
      PROD_HOST: ${BACKEND_URL}

    depends_on:
      - db
    links:
      - db:database
