version: '3.9'

services:

  # Database service
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: topsecret

  # Adminer for database management
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # Backend service
  backend:
    build: ../backend
    container_name: backend
    command: bash -c "sleep 3 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../backend:/backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: topsecret
      SPOTIFY_CLIENT_ID: c62a7c9ab8724af590583cf994eb285a
      SPOTIFY_CLIENT_SECRET: 3ffb6e9ee94b47788078cffdcdd6f31b
      OPENAI_API_KEY : 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

    depends_on:
      - db
    links:
      - db:database
