version: '3'

services:
  proxy:
    image: nginx
    container_name: proxy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "./proxy:/etc/nginx/templates"
    restart: always
    ports:
      - 80:80
      - 8080:8080
      - 8081:8081
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://backend:8000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}