# Generated by Django 5.0.4 on 2024-04-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_bibliosearchuser_book_lists_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklist',
            old_name='user_that_created_list',
            new_name='user',
        ),
    ]
