# Generated by Django 5.0.4 on 2024-04-27 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_that_created_list_booklist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bibliosearchuser'),
        ),
    ]
