# Generated by Django 5.0.4 on 2024-04-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_booklist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliosearchuser',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bibliosearchuser',
            name='surname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
