# Generated by Django 5.0.4 on 2024-04-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bibliosearchuser_name_bibliosearchuser_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliosearchuser',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bibliosearchuser',
            name='surname',
            field=models.CharField(max_length=100),
        ),
    ]
